[package]
edition = "2021"
name = "scape"
version = "0.0.1"

[dependencies]
bitflags = "2.4.1"
fps_ticker = { version = "1.0.0", optional = true }
image = { version = "0.24.6", default-features = false, optional = true }
tracing = { version = "0.1.37", features = [
    "max_level_trace",
    "release_max_level_debug",
] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
thiserror = "1"
xcursor = { version = "0.3.4", optional = true }
xkbcommon = "0.7.0"
renderdoc = { version = "0.11.0", optional = true }
clap = { version = "4.3.19", features = ["derive"] }
rlua = "0.20.0"
anyhow = "1.0.72"
puffin_http = { version = "0.16.0", optional = true }
profiling = { version = "1.0.13", optional = true }
bincode = "1.3.3"
calloop = { version = "*", features = ["executor"] }

[dependencies.smithay]
default-features = false
features = ["desktop", "wayland_frontend"]
# git = "https://github.com/smithay/smithay"
# rev = "3b3e07952e471618fe8b590ba3223f4201cec10c"
path = "../smithay"

[dependencies.smithay-drm-extras]
default-features = false
optional = true
# git = "https://github.com/smithay/smithay"
# rev = "3b3e07952e471618fe8b590ba3223f4201cec10c"
path = "../smithay/smithay-drm-extras"

[dependencies.x11rb]
default-features = false
features = ["composite"]
optional = true
version = "0.13.0"

[build-dependencies]
gl_generator = "0.14"

[features]
debug = ["fps_ticker", "image/png", "renderdoc"]
default = ["egl", "winit", "udev", "xwayland", "debug"]
egl = ["smithay/use_system_lib", "smithay/backend_egl"]
test_all_features = ["default", "debug"]
udev = [
    "smithay-drm-extras",
    "smithay/backend_libinput",
    "smithay/backend_udev",
    "smithay/backend_drm",
    "smithay/backend_gbm",
    "smithay/backend_vulkan",
    "smithay/backend_egl",
    "smithay/backend_session_libseat",
    "image",
    "smithay/renderer_gl",
    "smithay/renderer_pixman",
    "smithay/renderer_multi",
    "xcursor",
]
winit = ["smithay/backend_winit", "smithay/backend_drm"]
xwayland = [
    "smithay/xwayland",
    "x11rb",
    "smithay/x11rb_event_source",
    "xcursor",
]
profile-with-puffin = [
    "profiling",
    "profiling/profile-with-puffin",
    "puffin_http",
]
profile-with-tracy = ["profiling", "profiling/profile-with-tracy"]
# TODO: find out if this is useful
renderer_sync = []

[profile.release-with-debug]
inherits = "release"
debug = true
